spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spotify_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Creates or updates tables automatically
    show-sql: true      # Logs SQL queries
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  application:
    name: auth-service

  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: b5e154f9940b43a5a1463a4cfd2ae708
            client-secret: 7feb21f0179449f68baea8920f000e8f
            scope: user-library-read,user-read-recently-played,user-top-read
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/spotify"
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id
